{
 "title": "dashboard",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "tzone", "query": "${VAR_TZONE}" },
   { "name": "solcast_adj", "label": "solcast_adj", "query": "${VAR_SOLCAST_ADJ}" },
   { "name": "peak_I", "query": "${VAR_PEAK_I}" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Fault",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT \"Fault\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1 tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "State1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT \"State1\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1 tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "State2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT \"State2\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1 tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "State3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT  \"State3\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1 tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT  \"Status\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1 tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "ins",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Huawei_info",
     "query": "SELECT \"Insulation\" FROM \"Huawei_info\" WHERE $timeFilter and \"Insulation\" > 0 tz('${tzone}')",
     "select": [
      [
       { "params": [ "Insulation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "temp",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT max(\"Temp\") FROM \"Huawei\" WHERE time > now() -10m GROUP BY time(1d) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "wiring",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(q) from (SELECT (mean(\"U_A-B\") -  mean(\"M_U_AB\"))  / mean(\"I_A\")  as q FROM \"Huawei\" WHERE (\"I_A\" > 15) AND $timeFilter GROUP BY time(1d) fill(null)) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "last",
     "limit": "1",
     "measurement": "Huawei",
     "query": "SELECT \"M_P\" FROM \"Huawei\" WHERE $timeFilter ORDER BY time DESC LIMIT 1 tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" }
      ]
     ],
     "tz": "'${tzone}'"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "exp production 90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"power90\")) * $solcast_adj /3600   FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Daily total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT mean(\"P_daily\") FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(none) tz('${tzone}')",
     "select": [
      [
       { "params": [ "P_daily" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "${tzone}"
    },
    {
     "alias": "exp production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"power\"))   /3600 * $solcast_adj FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "exp production 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"power10\"))   /3600 * $solcast_adj FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "target": "sun_altitude" },
    {
     "alias": "balance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"M_P\")) /3600 / 1000  FROM \"Huawei\" WHERE $timeFilter and \"M_A-U\" != 0 GROUP BY time($__interval)  fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (integral(\"power90\")) * $solcast_adj /1800  FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT mean(\"P_active\")  as prod FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (integral(\"power\")) * $solcast_adj /1800  FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (integral(\"power10\")) * $solcast_adj /1800  FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"M_P\")) /3600000 - cumulative_sum(integral(\"P_active\")) /3600  FROM \"Huawei\" WHERE $timeFilter and \"M_A-U\" != 0 GROUP BY time($__interval)  fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "forecast",
     "query": "SELECT cumulative_sum(integral(\"power\")) / 3600 * $solcast_adj FROM \"forcast\" WHERE $timeFilter and time <= now() GROUP BY time(1d) fill(linear) tz('${tzone}') "
    },
    {
     "alias": "production",
     "query": "select max(p) from (SELECT last(\"P_daily\") as p FROM \"Huawei\" WHERE $timeFilter ) GROUP BY time(1d) tz('${tzone}') "
    },
    {
     "alias": "yesterday",
     "query": "SELECT max(\"P_daily\") - min(\"P_daily\")  FROM \"Huawei\" WHERE time >= now() -24h and  time <= ${__from}ms GROUP BY time(1d) fill(previous) order by time asc  tz('${tzone}') "
    },
    {
     "alias": "yet possible",
     "query": "SELECT cumulative_sum(integral(\"power\")) / 3600 * $solcast_adj as yet  FROM \"forcast\" WHERE time > now() and time < ${__to}ms  GROUP BY time(1h) fill(linear) tz('${tzone}') "
    },
    {
     "alias": "peak_max",
     "query": "select max(p) from (SELECT last(\"P_peak\") as p FROM \"Huawei\" WHERE $timeFilter ) GROUP BY time(1d) tz('${tzone}') "
    },
    {
     "query": "SELECT last(\"M_PTot\") - first(\"M_PTot\") as \"from grid\",  last(\"M_PExp\") - first(\"M_PExp\") as \"export\",  first(\"M_PTot\") - last(\"M_PTot\") + last(\"M_PExp\") - first(\"M_PExp\") as \"balance\", last(\"P_active\")  as \"Inverter\",  last(\"P_daily\") - (first(\"M_PTot\") - last(\"M_PTot\") + last(\"M_PExp\") - first(\"M_PExp\")) as \"load\",  last(\"P_daily\") - (last(\"M_PExp\") - first(\"M_PExp\")) as self_consumed FROM \"Huawei\" WHERE  $timeFilter  fill(previous) order by time asc tz('${tzone}')"
    },
    {
     "alias": "Year_Bal",
     "query": "select last(CBal) + last(DBal) as Year_Bal from (select cumulative_sum(diff)  as DBal from (SELECT (\"P_Exp\") - (\"P_Grid\") + (\"Adj\") as diff FROM \"Huawei_daily\"  fill(0)) where time > '${__to:date:YYYY-MM-18}' -61d), (select cumulative_sum(Bal) as CBal from Huawei_daily where time > now() -365d ) fill(previous) tz('${tzone}') "
    },
    {
     "alias": "off-grid",
     "query": "SELECT \"State3\" FROM \"Huawei_stat\" order by time desc limit 1 tz('${tzone}') "
    },
    {
     "alias": "grid-peak",
     "query": "SELECT min(\"M_P\")/(-1000) as peak FROM \"Huawei\" WHERE time > ${__from}ms  fill(none)  tz('${tzone}') "
    },
    {
     "alias": "pv_un",
     "query": "SELECT last(\"PV_Un\") FROM \"Huawei\" WHERE time > ${__from}ms -10m  fill(none) tz('${tzone}') "
    },
    {
     "query": "SELECT last(/load_(\\d)/)  FROM \"Huawei\" WHERE time > now() - 3d  fill(null) tz('${tzone}') "
    },
    {
     "alias": "meter",
     "query": "SELECT mean(\"M_A-U\") FROM \"Huawei\" WHERE time > ${__from}ms -10m  fill(0) tz('${tzone}') "
    },
    {
     "alias": "peak",
     "query": "select max(p) from (SELECT max(\"P_active\") as p FROM \"Huawei\" WHERE $timeFilter GROUP BY time(1d)) tz('${tzone}') "
    },
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT cumulative_sum(\"P_daily\") * 0.475 / 1000 FROM \"Huawei_daily\" WHERE time > '${__to:date:YYYY-01-01}'  fill(null)\n",
     "select": [
      [
       { "params": [ "P_daily" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    },
    {
     "alias": "trees",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT cumulative_sum(\"P_daily\") * 0.475 / 18.3  / 40 FROM \"Huawei_daily\" WHERE time > '${__to:date:YYYY-01-01}'  fill(null)\n",
     "select": [
      [
       { "params": [ "P_daily" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    },
    {
     "alias": "lifetime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "P_accum" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "f_ratio",
     "query": "SELECT last(\"f_ratio\") FROM \"Huawei_daily\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "U_A-B" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *$peak_I" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "I_A", "operator": ">", "value": "$peak_I - 0.05" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT max(\"P_active\") * 1000 FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT mean(\"P_active\") * 1000 FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "solcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT (integral(\"power\")) * $solcast_adj /1.8  FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "load_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"M_P\") - mean(\"P_active\") * 1000 FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "div_0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(load_0)  FROM \"Huawei\" WHERE $timeFilter GROUP BY time(30s) fill(none) tz('${tzone}')",
     "select": [
      [
       { "params": [ "load_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "div_1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(load_1)  FROM \"Huawei\" WHERE $timeFilter GROUP BY time(30s) fill(none) tz('${tzone}')",
     "select": [
      [
       { "params": [ "load_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "div_2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(load_2)  FROM \"Huawei\" WHERE $timeFilter GROUP BY time(30s) fill(none) tz('${tzone}')",
     "select": [
      [
       { "params": [ "load_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power (1h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"P_active\") FROM \"Huawei\" WHERE P_active > 0 and time > now() - 1h  GROUP BY time(30s) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "solcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (integral(\"power\")) * $solcast_adj / 1800  FROM \"forcast\" WHERE time > now() - 2h and time < now() + 1h GROUP BY time($__interval) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"M_P\") / 1000 - last(\"P_active\")  FROM \"Huawei\" WHERE time > now() - 1h  GROUP BY time(30s) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"M_P\") / 1000 FROM \"Huawei\" WHERE time > now() - 1h  GROUP BY time(30s) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "div_0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"load_0\") FROM \"Huawei\" WHERE time > now() - 1h  GROUP BY time(30s) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "div_1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"load_1\") FROM \"Huawei\" WHERE time > now() - 1h  GROUP BY time(30s) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "div_2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"load_2\") FROM \"Huawei\" WHERE time > now() - 1h  GROUP BY time(30s) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (integral(\"power10\")) * $solcast_adj / 1800  FROM \"forcast\" WHERE time > now() - 2h and time < now() + 1h GROUP BY time($__interval) fill(linear) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "suffix: kW" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"M_P\")  /1000  - last(\"P_active\")) as p FROM \"Huawei\" WHERE  time > now() - 5m  GROUP BY time(1m) fill(none) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"M_P\")  / 1000 FROM \"Huawei\" WHERE  time > now() - 5m GROUP BY time(1m) fill(none) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "grid (1h)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"M_P\")) / 3600 / 1000 FROM \"Huawei\" WHERE time > now() - 1h  GROUP BY time(1m) fill(none) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Forecast available daily for next week",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "forecast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "forcast",
     "query": "select last(f) from (SELECT cumulative_sum(integral(\"power\")) / 3600 / 6 * $solcast_adj as f FROM \"forcast\" WHERE (\"time\" > ${__from}ms) AND (\"time\" <= ${__from}ms + 6d)  GROUP BY time(1d) fill(linear) tz('${tzone}'))",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600 / 7" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "time", "operator": ">", "value": "${__from}ms" }
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "select last(l) from (SELECT  mean(\"P_Load\") as l FROM \"Huawei_daily\" WHERE time >  ${__from}ms - 7d and time <  ${__from}ms  GROUP BY time(1d) fill(linear) tz('${tzone}'))",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "10",
         2
        ],
        "type": "holt_winters_with_fit"
       }
      ]
     ]
    },
    {
     "alias": "var",
     "measurement": "Huawei_daily",
     "query": "select mean(var_err) as var from (SELECT cumulative_sum(\"P_daily\") / cumulative_sum(\"f_power\") / $solcast_adj as var_err  FROM \"Huawei_daily\" WHERE \"time\" >  ${__from}ms -7d and time < ${__from}ms  fill(linear) tz('${tzone}')) ",
     "select": [
      [
       { "params": [ "P_daily" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "time", "operator": ">", "value": "${__to} -7d" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "expiring",
     "query": "SELECT cumulative_sum(Bal)  FROM \"Huawei_daily\" where time > '${__to:date:YYYY-MM-18}' - 365d  and  time < '${__to:date:YYYY-MM-18}' - 305d   tz('${tzone}')"
    },
    {
     "alias": "year",
     "query": "select max(e) - max(g) from (select cumulative_sum(P_Exp) as e, cumulative_sum(P_Grid) as g from Huawei_daily where time > now() - 365d)"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "forecast",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "forecast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "forcast",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* $solcast_adj" ], "type": "math" }
      ]
     ],
     "tz": "${tzone}"
    },
    {
     "alias": "inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT mean(\"P_active\") FROM \"Huawei\" WHERE $timeFilter and time < ${__from}ms GROUP BY time(15m) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "today",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT mean(\"P_active\") FROM \"Huawei\" WHERE $timeFilter and time > ${__from}ms GROUP BY time(15m) fill(null) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "f_ratio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "select": [
      [
       { "params": [ "f_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "${tzone}"
    },
    {
     "alias": "forecast_max",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "forcast",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "${tzone}"
    }
   ]
  },
  {
   "title": "production balance",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select ((CBal) + (DBal)) * 1000 as Acct_Bal, Bal from (select cumulative_sum(diff)  as DBal from (SELECT (\"P_Exp\") - (\"P_Grid\") + (\"Adj\") as diff FROM \"Huawei_daily\"  fill(0)) where time > '${__to:date:YYYY-MM-18}' -61d), (select cumulative_sum(Bal) as CBal from Huawei_daily where time > now() -365d ), (select Bal from Huawei_daily where time > '${__to:date:YYYY-MM-18}' -61d)  fill(previous) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "balance ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select cumulative_sum(Bal) + cumulative_sum(Adj) from Huawei_daily where time > now() -365d fill(previous) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "daily production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "radiance",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "solar",
     "query": "SELECT first(\"radiance\") FROM \"solar\" WHERE time > now() - 61d  group by time(1d) fill(previous)  tz('${tzone}')",
     "select": [
      [
       { "params": [ "radiance" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "daily",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"P_daily\") FROM \"Huawei_daily\" WHERE time > now() - 31d tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "export",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (\"P_Exp\") as export FROM \"Huawei_daily\" WHERE time > now() - 31d tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"P_Grid\") FROM \"Huawei_daily\" WHERE time > now() - 31d tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT (\"P_Load\") FROM \"Huawei_daily\" WHERE time > now() - 31d tz('${tzone}')",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "Solcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT (\"f_power\") FROM \"Huawei_daily\" WHERE time > now() - 31d tz('${tzone}')",
     "select": [
      [
       { "params": [ "f_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"P_peak\") FROM \"Huawei_daily\" WHERE time > now() - 31d tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "peak grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"M_P\")/(-1000) FROM \"Huawei\" WHERE time > now() - 30d group by time(1d) fill(none) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "daily production (monthly)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "daily",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"P_daily\") FROM \"Huawei_daily\" where time >  '${__to:date:YYYY-MM-01}' - 451d  group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "export",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"P_Exp\") as export FROM \"Huawei_daily\" where time >  '${__to:date:YYYY-MM-01}' - 451d group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT mean(\"P_Load\") FROM \"Huawei_daily\"  where time >  '${__to:date:YYYY-MM-01}' - 451d group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"P_peak\") FROM \"Huawei_daily\"  where time >  '${__to:date:YYYY-MM-01}' - 451d group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"P_Grid\") FROM \"Huawei_daily\"  where time >  '${__to:date:YYYY-MM-01}' - 451d group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT mean(f_power) * mean(f_ratio) FROM \"Huawei_daily\"   where time >  '${__to:date:YYYY-MM-01}' - 451d GROUP BY time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "f_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast90",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT mean(\"f_power90\") * mean(f_ratio) FROM \"Huawei_daily\"  where time >  '${__to:date:YYYY-MM-01}' - 451d  GROUP BY time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "f_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "monthly production",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Month",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"P_daily\") FROM \"Huawei_daily\" where time > '${__to:date:YYYY-MM-18}' - 800d  group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "export",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"P_Exp\") as export FROM \"Huawei_daily\" where time > '${__to:date:YYYY-MM-18}' -800d  group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"f_power\")  * mean(f_ratio) FROM \"Huawei_daily\" where time > '${__to:date:YYYY-MM-18}' -800d  group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"P_Load\") FROM \"Huawei_daily\" where time > '${__to:date:YYYY-MM-18}' -800d  group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"P_Grid\") FROM \"Huawei_daily\" where time > '${__to:date:YYYY-MM-18}' -800d  group by time(30d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "balance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(Bal)  FROM \"Huawei_daily\" where time > '${__to:date:YYYY-MM-18}' - 365d tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "yearly production",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Year",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"P_daily\") FROM \"Huawei_daily\" where time >  '${__to:date:YYYY-01-01}' - 4382d group by time(365d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "export",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"P_Exp\") as export FROM \"Huawei_daily\" where time >  '${__to:date:YYYY-01-01}' - 4382d group by time(365d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"f_power\") * mean(f_ratio) FROM \"Huawei_daily\" where time >  '${__to:date:YYYY-01-01}' - 4382d group by time(365d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"P_Load\") FROM \"Huawei_daily\" where time >  '${__to:date:YYYY-01-01}' - 4382d group by time(365d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"P_Grid\") FROM \"Huawei_daily\" where time >  '${__to:date:YYYY-01-01}' - 4382d group by time(365d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "12 months",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Exports",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"M_PExp\") as f FROM \"Huawei\" WHERE time > now() - 366d ), (SELECT last(\"M_PExp\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"M_PTot\") as f FROM \"Huawei\" WHERE time > now() - 366d ), (SELECT last(\"M_PTot\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"P_accum\") as f FROM \"Huawei\" WHERE time > now() - 366d ), (SELECT last(\"P_accum\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "6 months",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Exports",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"M_PExp\") as f FROM \"Huawei\" WHERE time > now() - 181d  ), (SELECT last(\"M_PExp\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"M_PTot\") as f FROM \"Huawei\" WHERE time > now() - 181d  ), (SELECT last(\"M_PTot\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"P_accum\") as f FROM \"Huawei\" WHERE time > now() - 181d ), (SELECT last(\"P_accum\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "3 months",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Exports",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"M_PExp\") as f FROM \"Huawei\" WHERE time > now() - 91d ), (SELECT last(\"M_PExp\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"M_PTot\") as f FROM \"Huawei\" WHERE time > now() - 90d ), (SELECT last(\"M_PTot\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"P_accum\") as f FROM \"Huawei\" WHERE time > now() - 90d ), (SELECT last(\"P_accum\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "1 months",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Exports",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"M_PExp\") as f FROM \"Huawei\" WHERE time > now() - 31d ), (SELECT max(\"M_PExp\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"M_PTot\") as f FROM \"Huawei\" WHERE time > now() - 31d  and time < now() - 25d), (SELECT last(\"M_PTot\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select max(l) - min(f)  from (SELECT first(\"P_accum\") as f FROM \"Huawei\" WHERE time > now() - 31d  and time < now() - 25d), (SELECT last(\"P_accum\") as l  FROM \"Huawei\" WHERE time > now() - 1d) tz('${tzone}')",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "2d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT (\"P_daily\") FROM \"Huawei_daily\" tz('${tzone}')",
     "select": [
      [
       { "params": [ "P_daily" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}