{
 "title": "Solar",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Status",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Fault",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT \"Fault\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "State1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT \"State1\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "State2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT \"State2\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "State3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT  \"State3\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT  \"Status\"  FROM \"Huawei_stat\" where 'Status' != null order by time desc limit 1",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "ins",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_info",
     "select": [
      [
       { "params": [ "Insulation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "targets": [
    {
     "alias": "exp production 90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"power90\")) * 0.98 /3600   FROM \"forcast\" WHERE $timeFilter GROUP BY time(1m) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Daily total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT mean(\"P_daily\") FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "P_daily" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "UTC"
    },
    {
     "alias": "exp production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"power\"))   /3600 * 0.98  FROM \"forcast\" WHERE $timeFilter GROUP BY time(1m) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "exp production 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"power10\"))   /3600 * 0.98  FROM \"forcast\" WHERE $timeFilter GROUP BY time(1m) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "target": "sun_altitude" },
    {
     "alias": "production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select integral(prod) /300 from (SELECT mean(\"P_active\")  as prod FROM \"Huawei\" WHERE $timeFilter GROUP BY time(5m) fill(linear)) GROUP BY time(1m)   fill(previous) ",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "balance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"M_P\")) /3600 / 1000  FROM \"Huawei\" WHERE $timeFilter  GROUP BY time(1m)  fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (integral(\"power90\"))   /1800  FROM \"forcast\" WHERE $timeFilter GROUP BY time(1m) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"PV_P\") FROM \"Huawei\" order by time desc limit 1",
     "select": [
      [
       { "params": [ "PV_P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"P_active\") FROM \"Huawei\" order by time desc limit 1",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"M_P\")  / 1000 FROM \"Huawei\" order by time desc limit 1",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select p from (SELECT (last(\"M_P\")  /1000  - last(\"P_active\")) as p FROM \"Huawei\" ) limit 1",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(p) from (SELECT last(\"P_peak\") as p FROM \"Huawei\" WHERE time > now() - 5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Today",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(p) from (SELECT last(\"P_daily\") as p FROM \"Huawei\" WHERE time > now() - 5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Yesterday",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"P_daily\") -  first(\"P_daily\")  FROM \"Huawei\" WHERE time >= now() - 24h and  time <= now() GROUP BY time(1d) fill(previous) order by time asc limit 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Balance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select cumulative_sum(diff)  as balance from (SELECT first(\"P_Exp\") - first(\"P_Grid\") + first(\"Adj\") as diff FROM \"Huawei_daily\"  where time > now() -365d   GROUP BY time(1d) fill(0))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "From grid",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 3 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "tot0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT first(\"M_PTot\")  FROM \"Huawei\" WHERE  $timeFilter and  time > now() - 1d and P_daily = 0 and time < now() - 15m GROUP BY time(1d) fill(previous) order by time desc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "tot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"M_PTot\") FROM \"Huawei\"   GROUP BY  time(1d) fill(null) order by time desc limit 1",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Export",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 3 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "tot0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT first(\"M_PExp\")  FROM \"Huawei\" WHERE P_daily = 0  GROUP BY time(1d) fill(null) order by time asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "tot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"M_PExp\") FROM \"Huawei\"  GROUP BY  time(1d) fill(null) order by time desc limit 1",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Balance",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 3 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "tot0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT first(\"M_PTot\")  FROM \"Huawei\" WHERE  $timeFilter and  time > now() - 1d and P_daily = 0 and time < now() - 15m GROUP BY time(1d) fill(previous) order by time desc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "tot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"M_PTot\") FROM \"Huawei\"   GROUP BY  time(1d) fill(null) order by time desc limit 1",
     "select": [
      [
       { "params": [ "M_PTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "exp0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT first(\"M_PExp\")  FROM \"Huawei\" WHERE P_daily = 0  GROUP BY time(1d) fill(null) order by time asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "exp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"M_PExp\") FROM \"Huawei\"  GROUP BY  time(1d) fill(null) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 13, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "alias": "time",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT  last(\"P_accum\") FROM \"Huawei\" WHERE $timeFilter GROUP BY time(1s) fill(null) ",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Power reactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "P_reactive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "U_A-B" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "U_A" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "U_B" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "I_A" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "PV power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "PV_P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "PV voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "PV_Un" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "PV current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "PV_In" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "efficiency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "η" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "PF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "PF" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "Frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Frequency Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"M_Freq\") FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Lifetime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "P_accum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "alias": "Energy (1h)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(integral(\"M_P\")) / 3600 FROM \"Huawei\" WHERE time > now() - 1h  GROUP BY time(1m) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    },
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Power A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_A-P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Power B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_B-P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Power C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_C-P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Power Reactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_Pr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage AB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_U_AB" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage BC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_U_BC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage CA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_U_CA" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_A-U" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_B-U" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_C-U" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_A-I" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_B-I" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_C-I" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "PF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_PF" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"P_active\") FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"M_P\")  / 1000 FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"M_P\")  / 1000 - last(\"P_active\") FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "M_C-P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Reactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "P_reactive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"M_A-P\")  / 1000 FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "M_A-P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_B-P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_C-P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "solcast90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "forcast",
     "query": "SELECT first(\"power\")  / 1000 FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "power90" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "solcast10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "forcast",
     "query": "SELECT first(\"power\")  / 1000 FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "power10" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "solcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "forcast",
     "query": "SELECT first(\"power\")  / 1000 FROM \"forcast\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "daily production",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "radiance",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "solar",
     "query": "SELECT first(\"radiance\") FROM \"solar\" WHERE time > now() - 31d  group by time(1d) fill(previous)",
     "select": [
      [
       { "params": [ "radiance" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "daily",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"P_daily\") FROM \"Huawei_daily\" WHERE time > now() - 31d ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "export",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (\"P_Exp\") as export FROM \"Huawei_daily\" WHERE time > now() - 31d ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT (\"P_Load\") FROM \"Huawei_daily\" WHERE time > now() - 31d ",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"P_peak\") FROM \"Huawei_daily\" WHERE time > now() - 31d ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"P_Grid\") FROM \"Huawei_daily\" WHERE time > now() - 31d ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Solcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT (\"f_power\") FROM \"Huawei_daily\" WHERE time > now() - 31d",
     "select": [
      [
       { "params": [ "f_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "daily production (monthly)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "daily",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"P_daily\") FROM \"Huawei_daily\" group by time(30d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "export",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"P_Exp\") as export FROM \"Huawei_daily\" group by time(30d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT mean(\"P_Load\") FROM \"Huawei_daily\" group by time(30d) fill(none)",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    },
    {
     "alias": "peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"P_peak\") FROM \"Huawei_daily\" group by time(30d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"P_Grid\") FROM \"Huawei_daily\" group by time(30d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT mean(\"f_power\") FROM \"Huawei_daily\"  GROUP BY time(30d) fill(none)",
     "select": [
      [
       { "params": [ "f_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solcast90",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT mean(\"f_power90\") FROM \"Huawei_daily\"  GROUP BY time(30d) fill(none)",
     "select": [
      [
       { "params": [ "f_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "irradiance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "irradiance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT (\"P_daily\") / (\"P_peak\") FROM \"Huawei_daily\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "P_daily" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "irradiance fixed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "SELECT (\"P_daily\") / 8.76 FROM \"Huawei_daily\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "P_daily" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cummulative production",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "diff",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "select cumulative_sum(diff)  as balance from (SELECT first(\"P_Exp\") - first(\"P_Grid\") + first(\"Adj\") as diff FROM \"Huawei_daily\"   GROUP BY time(1d) fill(0))",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    },
    {
     "alias": "grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "select cumulative_sum(diff) as diff from (SELECT  first(\"P_Grid\") as diff FROM \"Huawei_daily\"   GROUP BY time(1d) fill(0)) ",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    },
    {
     "alias": "export",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei_daily",
     "query": "select cumulative_sum(diff) as balance from (SELECT first(\"P_Exp\") as diff FROM \"Huawei_daily\"   GROUP BY time(1d) fill(0)) ",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "AB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_U_AB" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "BC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_U_BC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "CA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_U_CA" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "reactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "P_reactive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "reactive grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_Pr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT moving_average(mean(\"M_A-U\"), 5) FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "M_A-U" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "20" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_B-U" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_C-U" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "reactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "P_reactive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "reactive grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_Pr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "grid power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "AB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "U_A-B" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "U_A" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "U_B" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "reactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "P_reactive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "A_g",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_A-U" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "U_A", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "B_g",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_B-U" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "U_B", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "inverter",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT mean(\"P_active\") *1000 FROM \"Huawei\" WHERE $timeFilter and \"P_active\" > 0 GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "meter",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT mean(\"P_active\") *1000 - mean(\"M_P\") FROM \"Huawei\" WHERE $timeFilter and 0 < \"M_P\"  GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "M_P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV_U",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"PV_Un\") FROM \"Huawei\" WHERE $timeFilter and \"PV_Un\" > 0 GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "currents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "c",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT min(\"M_A-I\") - mean(\"I_A\") + (min(\"M_C-I\") ) FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "M_A-I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "b",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT min(\"M_A-I\") - mean(\"I_A\") + (min(\"M_B-I\") - mean(\"I_A\")) FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "M_A-I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wiring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "Voltage diff",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select mean(q) from (SELECT (mean(\"U_A-B\") -  mean(\"M_U_AB\")) /  mean(\"M_U_AB\") *100 as q FROM \"Huawei\" WHERE (\"U_A-B\" > 10) AND $timeFilter GROUP BY time($__interval) fill(null)) GROUP BY time(10m)",
     "select": [
      [
       { "params": [ "U_A-B" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "U_A-B", "operator": ">", "value": "10" }
     ]
    },
    {
     "alias": "Inverter Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT moving_average(mean(\"I_A\"), 10) FROM \"Huawei\" WHERE (\"U_A-B\" > 10) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "I_A" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "U_A-B", "operator": ">", "value": "10" }
     ]
    },
    {
     "alias": "wiring losses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select mean(q) from (SELECT (mean(\"U_A-B\") -  mean(\"M_U_AB\"))  * mean(\"I_A\") as q FROM \"Huawei\" WHERE (\"I_A\" > 15) AND $timeFilter GROUP BY time($__interval) ) GROUP BY time(10m)",
     "select": [
      [
       { "params": [ "I_A" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "U_A-B", "operator": ">", "value": "10" }
     ]
    },
    {
     "alias": "wiring resistance  (mΩ)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "select mean(q) from (SELECT (mean(\"U_A-B\") -  mean(\"M_U_AB\"))  / mean(\"I_A\") * 1000 as q FROM \"Huawei\" WHERE (\"I_A\" > 15) AND $timeFilter GROUP BY time($__interval) fill(null)) GROUP BY time(10m)",
     "select": [
      [
       { "params": [ "I_A" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "U_A-B", "operator": ">", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "M_Freq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "Frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Frequency", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "efficiency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "η",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT last(\"η\") FROM \"Huawei\" WHERE $timeFilter  and \"η\" > 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "η" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "p",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "select": [
      [
       { "params": [ "PV_P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "PV_P", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT min(\"M_A-I\") - mean(\"I_A\") + (min(\"M_B-I\") - mean(\"I_A\")) FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "p",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Huawei",
     "query": "SELECT min(\"M_A-I\") - mean(\"I_A\") + (min(\"M_B-I\") - mean(\"I_A\")) FROM \"Huawei\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "P_active" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}